#!/usr/bin/env nextflow
nextflow.enable.dsl=2
/*
========================================================================================
                        nf-core/hostfinder
========================================================================================
nf-core/hostfinder Analysis Pipeline.
#### Homepage / Documentation
https://github.com/nf-core/hostfinder
----------------------------------------------------------------------------------------
*/

def helpMessage() {
    // TODO nf-core: Add to this help message with new command line parameters
    log.info nfcoreHeader()
    log.info"""

    Usage:

    The typical command for running the pipeline is as follows:

    nextflow run nf-core/hostfinder --reads '*_R{1,2}.fastq.gz' -profile docker

    Mandatory arguments:
        --mode [str]                    Mode to run the pipeline in. Choose either 'train' or 'test'
        -profile [str]                  Configuration profile to use. Can use multiple (comma separated)
                                        Available: conda, docker, singularity, test, awsbatch, <institute> and more

        Training Pipeline Options:
        --assembly_dir                  Directory of your fasta files (full path required) [./data/test/model_build_in/assemblies]
        --hostdata_file                 CSV file containing assembly filename, host, year and region [./test_data/model_build_in/metadata.csv]
        
        Testing Pipeline Options:
        --assembly_dir                  Directory of your fasta files (full path required) [input_test]
        --pangenome_models_dir          Folder of pangenome models (generated by previous pipeline) [out/4.model/pangenome_models]  
        --pangenome_reference_folder    Reference genome for pangenome (panaroo-integrate) [ ]  
        --pangenome_thresholds_file     Thresholds file for pangenome model (generated by previous pipeline) [out/4.model/pangenome_models/model_thresholds.csv]
        --model_features_file           Features file for pangenome model (generated by previous pipeline) [out/4.model/pangenome_models/model_features.csv]  
        --wgmlst_models_dir             Folder of wgMLST models (generated by previous pipeline) [out/4.model/wgmlst_models] 
        --wgmlst_reference_file         pyMLST wgMLST schema used for training (mlst --scheme) [data/ref/Escherichia_coli] 
        --wgmlst_thresholds_file        Thresholds file for wgMLST model (generated by previous pipeline) [out/4.model/wgmlst_models/model_thresholds.csv]

    Training Options:
        Tool Options:
        --panaroo_mode                  Panaroo assembly filtering mode (panaroo --clean-mode) ["moderate"]
        --panaroo_threads               Num of threads to use for panaroo (panaroo -t) [10]

        Input file Options:
        --assembly_column               Column name of your assemblies. Must contain extension eg myassembly.fasta ["Filename"]
        --host_column                   Column name of your hosts ["Host"]
        --region_column                 Column of region of origin. Used to detect clonal clusters. Can be empty, but must exist. ["Region"]
        --year_collection               Column of year each assembly was collected. Used to detect clonal clusters. Can be empty, but must exist. ["Year"]

        Assembly Quality Parameters:
        --as_ln_upr                     Maximum accepted assembly length [6000000]
        --as_ln_lwr                     Minimum accepted assembly length [4000000]
        --ctg_count                     Minimum accepted number of contigs [500]
        --largest_ctg                   Minimum accepted length of largest contig [100000] 
        --n50                           Minimum accepted n50 [50000]
        --gc_upr                        Maximum accepted GC % [54]
        --gc_lwr                        Minimum accepted GC % [50]
        
        Clonal Detection Parameters:
        --snp_dist_threshold            SNP difference used to detect clonal clusters. Used in conjunction with region & collection year metadata. [10]

        Other Parameters:
        --panaroo_batch_size            Number of samples to process in each panaroo batch [500]
        
    Testing Options:
        --panaroo_threads               Num of threads to use for panaroo (panaroo -t) [10]
    
        --test_pangenome                Run pangenome testing pipeline [true]
        --test_wgmlst                   Run wgMLST testing pipeline [true]   


    References:
        --prokka_ref_file               'Trusted' protein file for prokka (prokka --proteins) [data/ref/EC958_SNIPPYREF.chr.fa]
        --snp_ref_file                  Reference file for snippy (snippy --ref) [./data/ref/EC958_SNIPPYREF.chr.fa]

    Other options:
        --assembly_extension            Extension of your assembly files [fasta]
        --outdir [file]                 The output directory where the results will be saved
        --email [email]                 Set this parameter to your e-mail address to get a summary e-mail with details of the run sent to you when the workflow exits
        --email_on_fail [email]         Same as --email, except only send mail if the workflow is not successful
        -name [str]                     Name for the pipeline run. If not specified, Nextflow will automatically generate a random mnemonic

    AWSBatch options:
        --awsqueue [str]                The AWSBatch JobQueue that needs to be set when running on AWSBatch
        --awsregion [str]               The AWS Region for your AWS Batch job to run on
        --awscli [str]                  Path to the AWS CLI tool
    """.stripIndent()
}

// Show help message
if (params.help) {
    helpMessage()
    exit 0
}

/*
 * SET UP CONFIGURATION VARIABLES
 */

// TODO Remove?
// Check if genome exists in the config file
//if (params.genomes && params.genome && !params.genomes.containsKey(params.genome)) {
//    exit 1, "The provided genome '${params.genome}' is not available in the iGenomes file. Currently the available genomes are ${params.genomes.keySet().join(", ")}"
//}
// T/ODO nf-core: Add any reference files that are needed
// Configurable reference genomes
//
// NOTE - THIS IS NOT USED IN THIS PIPELINE, EXAMPLE ONLY
// If you want to use the channel below in a process, define the following:
//   input:
//   file fasta from ch_fasta
//
//params.fasta = params.genome ? params.genomes[ params.genome ].fasta ?: false : false
//if (params.fasta) { ch_fasta = file(params.fasta, checkIfExists: true) }

// Has the run name been specified by the user?
//  this has the bonus effect of catching both -name and --name
custom_runName = params.name
if (!(workflow.runName ==~ /[a-z]+_[a-z]+/)) {
    custom_runName = workflow.runName
}

if (workflow.profile.contains('awsbatch')) {
    // AWSBatch sanity checking
    if (!params.awsqueue || !params.awsregion) exit 1, "Specify correct --awsqueue and --awsregion parameters on AWSBatch!"
    // Check outdir paths to be S3 buckets if running on AWSBatch
    // related: https://github.com/nextflow-io/nextflow/issues/813
    if (!params.outdir.startsWith('s3:')) exit 1, "Outdir not on S3 - specify S3 Bucket to run on AWSBatch!"
    // Prevent trace files to be stored on S3 since S3 does not support rolling files.
    if (params.tracedir.startsWith('s3:')) exit 1, "Specify a local tracedir or run without trace! S3 cannot be used for tracefiles."
}

// Stage config files
//ch_multiqc_config = file("$baseDir/assets/multiqc_config.yaml", checkIfExists: true)
//ch_multiqc_custom_config = params.multiqc_config ? Channel.fromPath(params.multiqc_config, checkIfExists: true) : Channel.empty()
//ch_output_docs = file("$baseDir/docs/output.md", checkIfExists: true)
panaroo_merge_script = file("${workflow.projectDir}/bin/panaroo_merge_process.py",checkIfExists: true)
model_test_wgmlst_script = file("${workflow.projectDir}/bin/model_test_wgmlst.py",checkIfExists: true)
model_test_pangenome_script = file("${workflow.projectDir}/bin/model_test_pangenome.py",checkIfExists: true)

/*
 * Create a channel for input read files
 */
ch_assemblies = channel
    .fromPath("${params.assembly_dir}/*.${params.assembly_extension}")
    .ifEmpty { exit 1, "--assembly_dir was empty - Please specify --assembly_dir for the directory containing your assemblies" }  

if (params.mode=="train"){
    if (params.hostdata_file) {
        hostdata_file = file(params.hostdata_file,checkIfExists: true)
    } else { 
        exit 1, "--snp_ref_file was empty Please specify --hostdata_file for the CSV file containing assembly filename, host, year and region"
    }

    if (params.prokka_ref_file) {
        prokka_ref_file = file(params.prokka_ref_file,checkIfExists: true)
    } else { 
        exit 1, "--prokka_ref_file was empty Please specify --prokka_ref_file for the CSV file containing assembly filename, host, year and region"
    }

    if (params.snp_ref_file) {
        snp_ref_file = file(params.snp_ref_file,checkIfExists: true)
    } else { 
        exit 1, "--snp_ref_file was empty Please specify --snp_ref_file for the CSV file containing assembly filename, host, year and region"
    }

} else if (params.mode=="test"){

    if (params.test_pangenome) {
        if (params.pangenome_reference_folder) {
            // Use .first() to convert queue channel to value channel so it can be reused for each sample
            pangenome_reference_folder = Channel
                .fromPath("${params.pangenome_reference_folder}", type:'dir', checkIfExists: true)
                .first()
            model_features_file = file(params.model_features_file,checkIfExists: true)
        }
        if (params.prokka_ref_file) {
            prokka_ref_file = file(params.prokka_ref_file,checkIfExists: true)
        } else { 
            exit 1, "--prokka_ref_file was empty Please specify --prokka_ref_file"
        }
        if (params.pangenome_thresholds_file) {
            pangenome_thresholds_file = file(params.pangenome_thresholds_file,checkIfExists: true)
        } else { 
            exit 1, "--pangenome_thresholds_file was empty Please specify --pangenome_thresholds_file"
        }
        if (params.model_features_file) {
            model_features_file = file(params.model_features_file,checkIfExists: true)
        } else { 
            exit 1, "--model_features_file was empty Please specify --model_features_file"
        }
        ch_pangenome_models = Channel
            .fromPath(params.pangenome_models_dir, checkIfExists: true)
            .ifEmpty { error "Input directory ${params.pangenome_models_dir} does not exist!" }
    }

    if (params.test_wgmlst) {
        if (params.wgmlst_reference_file) {
            wgmlst_reference_file = file(params.wgmlst_reference_file)
        } else { 
            exit 1, "--wgmlst_reference_file was empty Please specify --wgmlst_reference_file"
        }
        if (params.wgmlst_thresholds_file) {
            wgmlst_thresholds_file = file(params.wgmlst_thresholds_file,checkIfExists: true)
        } else { 
            exit 1, "--wgmlst_thresholds_file was empty Please specify --wgmlst_thresholds_file"
        }
        ch_wgmlst_models_path = Channel
            .fromPath(params.wgmlst_models_dir, checkIfExists: true)
            .ifEmpty { error "Input directory ${params.wgmlst_models_dir} does not exist!" }
    }

    if (!params.assembly_dir) {
        exit 1, "Please specify --assembly_dir for the directory containing your assemblies"
    }

} else {
    exit 1, "Please specify a valid --mode to run the pipeline in. Choose either 'train' or 'test'"
}



// Header log info
log.info nfcoreHeader()
def summary = [:]
if (workflow.revision) summary['Pipeline Release'] = workflow.revision
summary['Run Name']         = custom_runName ?: workflow.runName
// TODO nf-core: Report custom parameters here
summary['Mode']            = params.mode
if (params.mode=="train"){
    summary['Assembly Directory'] = params.assembly_dir
    summary['Hostdata File']      = params.hostdata_file
    summary['Assembly Column']    = params.assembly_column
    summary['Host Column']        = params.host_column
    summary['Region Column']      = params.region_column
    summary['Year Column']    = params.year_column
    summary['Panaroo Clean Mode'] = params.panaroo_mode
    summary['Panaroo Threads']    = params.panaroo_threads
    summary['Assembly Length Upper'] = params.as_ln_upr
    summary['Assembly Length Lower'] = params.as_ln_lwr
    summary['Contig Count']       = params.ctg_count
    summary['Largest Contig']     = params.largest_ctg
    summary['N50']                = params.n50
    summary['GC Upper']           = params.gc_upr
    summary['GC Lower']           = params.gc_lwr
    summary['SNP Distance Threshold'] = params.snp_dist_threshold
    summary['Prokka Reference'] = params.prokka_ref_file
    summary['Snippy Reference']  = params.snp_ref_file

} else if (params.mode=="test") {  
    summary['Assembly Directory']     = params.assembly_dir
    if (params.test_pangenome) {
        summary['Pangenome Models Directory'] = params.pangenome_models_dir
        summary['Pangenome Reference Folder']   = params.pangenome_reference_folder
        summary['Panaroo Threads']            = params.panaroo_threads
        summary['Prokka Reference']           = params.prokka_ref_file
    }
    if (params.test_wgmlst) {
        summary['wgMLST Models Directory']    = params.wgmlst_models_dir
        summary['wgMLST Reference File']      = params.wgmlst_reference_file
    }
}
summary['Max Resources']    = "$params.max_memory memory, $params.max_cpus cpus, $params.max_time time per job"
if (workflow.containerEngine) summary['Container'] = "$workflow.containerEngine - $workflow.container"
summary['Output dir']       = params.outdir
summary['Launch dir']       = workflow.launchDir
summary['Working dir']      = workflow.workDir
summary['Script dir']       = workflow.projectDir
summary['User']             = workflow.userName
if (workflow.profile.contains('awsbatch')) {
    summary['AWS Region']   = params.awsregion
    summary['AWS Queue']    = params.awsqueue
    summary['AWS CLI']      = params.awscli
}
summary['Config Profile'] = workflow.profile
if (params.config_profile_description) summary['Config Description'] = params.config_profile_description
if (params.config_profile_contact)     summary['Config Contact']     = params.config_profile_contact
if (params.config_profile_url)         summary['Config URL']         = params.config_profile_url
if (params.email || params.email_on_fail) {
    summary['E-mail Address']    = params.email
    summary['E-mail on failure'] = params.email_on_fail
    summary['MultiQC maxsize']   = params.max_multiqc_email_size
}
log.info summary.collect { k,v -> "${k.padRight(18)}: $v" }.join("\n")
log.info "-\033[2m--------------------------------------------------\033[0m-"

// Check the hostnames against configured profiles
checkHostname()

Channel.from(summary.collect{ [it.key, it.value] })
    .map { k,v -> "<dt>$k</dt><dd><samp>${v ?: '<span style=\"color:#999999;\">N/A</a>'}</samp></dd>" }
    .reduce { a, b -> return [a, b].join("\n            ") }
    .map { x -> """
    id: 'nf-core-hostfinder-summary'
    description: " - this information is collected when the pipeline is started."
    section_name: 'nf-core/hostfinder Workflow Summary'
    section_href: 'https://github.com/nf-core/hostfinder'
    plot_type: 'html'
    data: |
        <dl class=\"dl-horizontal\">
            $x
        </dl>
    """.stripIndent() }
    .set { ch_workflow_summary }

/*
 * Parse software version numbers
 */
process get_software_versions {
    publishDir "${params.outdir}/pipeline_info", mode: 'copy',
        saveAs: { filename ->
                    if (filename.indexOf(".csv") > 0) filename
                    else null
                }

    output:
    file 'software_versions_mqc.yaml'
    file "software_versions.csv"

    script:
    // TODO nf-core: Get all tools to print their version number here
    """
    echo $workflow.manifest.version > v_pipeline.txt
    echo $workflow.nextflow.version > v_nextflow.txt
    prokka --version > v_prokka.txt
    quast --version > v_quast.txt
    panaroo --version > v_panaroo.txt
    snippy --version > v_snippy.txt
    pymlst --version > v_pymlst.txt
    snp-dists --version > v_snp-dists.txt
    pip show --version scikit-learn > v_scikit-learn.txt
    pip show --version networkx > v_networkx.txt
    scrape_software_versions.py &> software_versions_mqc.yaml
    """
}

// Modules 
include { module_quast                      } from "$projectDir/modules/module_quast.nf"
include { module_qc_filter                  } from "$projectDir/modules/module_qc_filter.nf"
include { module_prokka                     } from "$projectDir/modules/module_prokka.nf"
include { module_snippy                     } from "$projectDir/modules/module_snippy.nf"
include { module_file_batch                 } from "$projectDir/modules/module_file_batch.nf"
include { module_panaroo_batch              } from "$projectDir/modules/module_panaroo_batch.nf"
include { module_panaroo_merge              } from "$projectDir/modules/module_panaroo_merge.nf"
include {module_pangenome_integrate         } from "$projectDir/modules/module_pangenome_integrate.nf"
include {module_pangenome_match             } from "$projectDir/modules/module_pangenome_match.nf"
include {module_pangenome_merge             } from "$projectDir/modules/module_pangenome_merge.nf"
include { module_pymlst_assign              } from "$projectDir/modules/module_pymlst_assign.nf"
include { module_wgmlst_merge               } from "$projectDir/modules/module_wgmlst_merge.nf"
include { module_pymlst_predict             } from "$projectDir/modules/module_pymlst_predict.nf"
include { module_pangenome_predict          } from "$projectDir/modules/module_pangenome_predict.nf"
// TODO nf-core: Add other modules here

/*
 * Main workflow
 */

workflow train_single_seq {
            take:
                ch_assemblies
                hostdata_file
            main:
                module_quast(ch_assemblies)
                module_qc_filter(
                    module_quast.out.collectFile(keepHeader:true, skip:1, sort:true,storeDir:"${params.outdir}/1.assembly_quality"), 
                    hostdata_file,
                    file(params.assembly_dir),
                    params.assembly_extension,
                    params.as_ln_upr,
                    params.as_ln_lwr,
                    params.ctg_count,
                    params.largest_ctg,
                    params.n50,
                    params.gc_upr,
                    params.gc_lwr
                    )
                module_prokka(
                    module_qc_filter.out.good_assemblies.flatten(), 
                    prokka_ref_file) 
                module_snippy(
                    module_qc_filter.out.good_assemblies.flatten(), 
                    snp_ref_file)
            emit:
                good_assemblies_list = module_qc_filter.out.good_assemblies_list 
                good_metadata = module_qc_filter.out.good_metadata
                annotations = module_prokka.out.annotation.collect()
                snps = module_snippy.out.collect()
        }


workflow batch_operations {
            take: // TODO Add option tos uplly previous directory of runs
                good_assemblies_list // printqc.out.good_assemblies_list 
                good_metadata //printqc.out.good_metadata
                annotations //module_prokka.out.annotation.collect()
                snps //module_snippy.out.collect()
                

            main:
                module_file_batch(annotations, params.panaroo_batch_size)

                module_panaroo_batch(module_file_batch.out.folders.flatten(),
                    params.panaroo_threads)

                module_panaroo_merge(module_panaroo_batch.out.collect(),
                    params.panaroo_threads) 

                /* module_panaroo_merge(panaroo_batch.out.batch_results.collect())

                snippy_core(
                    snps, 
                    snp_ref_file) //TODO add snippy core
                snp_dists(snippy_core.out.aligned_snps)
                clonal_detection(
                    clonal_detection_script, 
                    good_metadata, 
                    snp_dists.out) // TODO add clonal detection script
                clonal_filtering(
                    clonal_detection.out.clusters, 
                    good_assemblies_list, // TODO change to input custom good assemblies file (?)
                    good_metadata) //c TODO hange to input metadat file
                module_pymlst_assign(
                    module_qc_filter.out.good_assemblies.flatten(), 
                    module_pymlst_schema.out.schema) //TODO add pymlst assignment
                module_pymlst_schema(
                    ) //TODO add pymlst schema creation
                model_training(_ //TODO)


            emit: //TODO CHECK
                pangenome_csv = panaroo.out.pv_csv
                pangenome_rtab = panaroo.out.pv_rtab
                pv_ref = panaroo.out.pv_ref
                core_snps = snippy_core.out.core_snps
                clonal_filtering_out = clonal_filtering.out
                */
        }

workflow {
    main:

    if (params.mode=="train"){
        train_single_seq(ch_assemblies,hostdata_file)

        batch_operations(
            train_single_seq.out.good_assemblies_list, 
            train_single_seq.out.good_metadata, 
            train_single_seq.out.annotations, 
            train_single_seq.out.snps)

    }
    else if (params.mode=="test"){

        module_quast(ch_assemblies) 

        if (params.test_pangenome){

            module_prokka(ch_assemblies, 
                        prokka_ref_file)
            
            module_pangenome_integrate(module_prokka.out.annotation.flatten(),
                pangenome_reference_folder,
                params.panaroo_threads)

            module_pangenome_match(
                panaroo_merge_script,
                module_pangenome_integrate.out.gene_data_file_ref,
                module_pangenome_integrate.out.gml_file_ref,
                model_features_file,
                module_pangenome_integrate.out.test_dir
            )

            module_pangenome_merge(
                module_pangenome_match.out.matched_presence_absence.collect()
            )

            module_pangenome_predict(
                model_test_pangenome_script,
                module_pangenome_merge.out.merged_pangenome,
                ch_pangenome_models,
                pangenome_thresholds_file
            )
        }
        if (params.test_wgmlst){
            module_pymlst_assign(
                ch_assemblies.flatten(),
                wgmlst_reference_file
                )

            module_wgmlst_merge(
                module_pymlst_assign.out.wgmlst_single.collect()
            )

            module_pymlst_predict(
                model_test_wgmlst_script,
                module_wgmlst_merge.out.merged_wgmlst,
                ch_wgmlst_models_path,
                wgmlst_thresholds_file

            )
        }
    }
}




/*
 * Completion e-mail notification
 */
workflow.onComplete {

    // Set up the e-mail variables
    def subject = "[nf-core/hostfinder] Successful: $workflow.runName"
    if (!workflow.success) {
        subject = "[nf-core/hostfinder] FAILED: $workflow.runName"
    }
    def email_fields = [:]
    email_fields['version'] = workflow.manifest.version
    email_fields['runName'] = custom_runName ?: workflow.runName
    email_fields['success'] = workflow.success
    email_fields['dateComplete'] = workflow.complete
    email_fields['duration'] = workflow.duration
    email_fields['exitStatus'] = workflow.exitStatus
    email_fields['errorMessage'] = (workflow.errorMessage ?: 'None')
    email_fields['errorReport'] = (workflow.errorReport ?: 'None')
    email_fields['commandLine'] = workflow.commandLine
    email_fields['projectDir'] = workflow.projectDir
    email_fields['summary'] = summary
    email_fields['summary']['Date Started'] = workflow.start
    email_fields['summary']['Date Completed'] = workflow.complete
    email_fields['summary']['Pipeline script file path'] = workflow.scriptFile
    email_fields['summary']['Pipeline script hash ID'] = workflow.scriptId
    if (workflow.repository) email_fields['summary']['Pipeline repository Git URL'] = workflow.repository
    if (workflow.commitId) email_fields['summary']['Pipeline repository Git Commit'] = workflow.commitId
    if (workflow.revision) email_fields['summary']['Pipeline Git branch/tag'] = workflow.revision
    email_fields['summary']['Nextflow Version'] = workflow.nextflow.version
    email_fields['summary']['Nextflow Build'] = workflow.nextflow.build
    email_fields['summary']['Nextflow Compile Timestamp'] = workflow.nextflow.timestamp

/*
    // TODO nf-core: If not using MultiQC, strip out this code (including params.max_multiqc_email_size)
    // On success try attach the multiqc report
    def mqc_report = null
    try {
        if (workflow.success) {
            mqc_report = ch_multiqc_report.getVal()
            if (mqc_report.getClass() == ArrayList) {
                log.warn "[nf-core/hostfinder] Found multiple reports from process 'multiqc', will use only one"
                mqc_report = mqc_report[0]
            }
        }
    } catch (all) {
        log.warn "[nf-core/hostfinder] Could not attach MultiQC report to summary email"
    }

    // Check if we are only sending emails on failure
    email_address = params.email
    if (!params.email && params.email_on_fail && !workflow.success) {
        email_address = params.email_on_fail
    }

    // Render the TXT template
    def engine = new groovy.text.GStringTemplateEngine()
    def tf = new File("$baseDir/assets/email_template.txt")
    def txt_template = engine.createTemplate(tf).make(email_fields)
    def email_txt = txt_template.toString()

    // Render the HTML template
    def hf = new File("$baseDir/assets/email_template.html")
    def html_template = engine.createTemplate(hf).make(email_fields)
    def email_html = html_template.toString()

    // Render the sendmail template
    def smail_fields = [ email: email_address, subject: subject, email_txt: email_txt, email_html: email_html, baseDir: "$baseDir", mqcFile: mqc_report, mqcMaxSize: params.max_multiqc_email_size.toBytes() ]
    def sf = new File("$baseDir/assets/sendmail_template.txt")
    def sendmail_template = engine.createTemplate(sf).make(smail_fields)
    def sendmail_html = sendmail_template.toString()

    // Send the HTML e-mail
    if (email_address) {
        try {
            if (params.plaintext_email) { throw GroovyException('Send plaintext e-mail, not HTML') }
            // Try to send HTML e-mail using sendmail
            [ 'sendmail', '-t' ].execute() << sendmail_html
            log.info "[nf-core/hostfinder] Sent summary e-mail to $email_address (sendmail)"
        } catch (all) {
            // Catch failures and try with plaintext
            [ 'mail', '-s', subject, email_address ].execute() << email_txt
            log.info "[nf-core/hostfinder] Sent summary e-mail to $email_address (mail)"
        }
    }

    // Write summary e-mail HTML to a file
    def output_d = new File("${params.outdir}/pipeline_info/")
    if (!output_d.exists()) {
        output_d.mkdirs()
    }
    def output_hf = new File(output_d, "pipeline_report.html")
    output_hf.withWriter { w -> w << email_html }
    def output_tf = new File(output_d, "pipeline_report.txt")
    output_tf.withWriter { w -> w << email_txt }

    c_green = params.monochrome_logs ? '' : "\033[0;32m";
    c_purple = params.monochrome_logs ? '' : "\033[0;35m";
    c_red = params.monochrome_logs ? '' : "\033[0;31m";
    c_reset = params.monochrome_logs ? '' : "\033[0m";

    if (workflow.stats.ignoredCount > 0 && workflow.success) {
        log.info "-${c_purple}Warning, pipeline completed, but with errored process(es) ${c_reset}-"
        log.info "-${c_red}Number of ignored errored process(es) : ${workflow.stats.ignoredCount} ${c_reset}-"
        log.info "-${c_green}Number of successfully ran process(es) : ${workflow.stats.succeedCount} ${c_reset}-"
    }

    if (workflow.success) {
        log.info "-${c_purple}[nf-core/hostfinder]${c_green} Pipeline completed successfully${c_reset}-"
    } else {
        checkHostname()
        log.info "-${c_purple}[nf-core/hostfinder]${c_red} Pipeline completed with errors${c_reset}-"
    }
*/
}


def nfcoreHeader() {
    // Log colors ANSI codes
    c_black = params.monochrome_logs ? '' : "\033[0;30m";
    c_blue = params.monochrome_logs ? '' : "\033[0;34m";
    c_cyan = params.monochrome_logs ? '' : "\033[0;36m";
    c_dim = params.monochrome_logs ? '' : "\033[2m";
    c_green = params.monochrome_logs ? '' : "\033[0;32m";
    c_purple = params.monochrome_logs ? '' : "\033[0;35m";
    c_reset = params.monochrome_logs ? '' : "\033[0m";
    c_white = params.monochrome_logs ? '' : "\033[0;37m";
    c_yellow = params.monochrome_logs ? '' : "\033[0;33m";

    return """    -${c_dim}--------------------------------------------------${c_reset}-
                                            ${c_green},--.${c_black}/${c_green},-.${c_reset}
    ${c_blue}        ___     __   __   __   ___     ${c_green}/,-._.--~\'${c_reset}
    ${c_blue}  |\\ | |__  __ /  ` /  \\ |__) |__         ${c_yellow}}  {${c_reset}
    ${c_blue}  | \\| |       \\__, \\__/ |  \\ |___     ${c_green}\\`-._,-`-,${c_reset}
                                            ${c_green}`._,._,\'${c_reset}
    ${c_purple}  nf-core/hostfinder v${workflow.manifest.version}${c_reset}
    -${c_dim}--------------------------------------------------${c_reset}-
    """.stripIndent()
}

def checkHostname() {
    def c_reset = params.monochrome_logs ? '' : "\033[0m"
    def c_white = params.monochrome_logs ? '' : "\033[0;37m"
    def c_red = params.monochrome_logs ? '' : "\033[1;91m"
    def c_yellow_bold = params.monochrome_logs ? '' : "\033[1;93m"
    if (params.hostnames) {
        def hostname = "hostname".execute().text.trim()
        params.hostnames.each { prof, hnames ->
            hnames.each { hname ->
                if (hostname.contains(hname) && !workflow.profile.contains(prof)) {
                    log.error "====================================================\n" +
                            "  ${c_red}WARNING!${c_reset} You are running with `-profile $workflow.profile`\n" +
                            "  but your machine hostname is ${c_white}'$hostname'${c_reset}\n" +
                            "  ${c_yellow_bold}It's highly recommended that you use `-profile $prof${c_reset}`\n" +
                            "============================================================"
                }
            }
        }
    }
}
